### ISSUE TITLE
Verification for unselected condition of checkbox doesn't work properly

### ISSUE THREAD

**Issue by greenhairedlime** [strongqa/howitzer#224] opened 2017-05-18 19:18 UTC
Execution of `has_select_first_dataset_element?(unchecked: true)` led to the following error
**Backtrace:**
_ArgumentError: invalid keys :unchecked, should be one of :count, :minimum, :maximum, :between, :text, :id, :class, :visible, :exact, :exact_text, :match, :wait, :filter_set_

**Comment by greenhairedlime** [comment] 2017-06-23 13:18
**Additional information:**
Initialization of element: `element :select_first_dataset,            :xpath, '//tr[1]/td[1]/span/input'`
Capybara version: `capybara (2.14.3)`

**Comment by Lec1k** [comment] 2017-06-26 09:48
@greenhairedlime, you should add :checkbox to element definition:

**Comment by romikoops** [comment] 2017-06-27 09:25
@greenhairedlime @Lec1k 
After quick capybara code investigation, I have found following information:

1. originally, the issue is not related with Howitzer implementation. It if fully depends on Capybara implementation. So, in fact we just proxy arguments from our DSL method `element`. In current issue, Capybara does not allow to apply `unchecked` filter for :xpath selector

2. List of supported Capybara selectors is possible to find here https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector.rb
We can see, `:checked` filter is included to FilterSet `_field` (:field, :radio_button, :checkbox)

As a prove, following code perfectly works:

```ruby
# /web/pages/login_page.rb
class LoginPage < Howitzer::Web::Page
  # ...
  element :remember_me, :checkbox, 'user_remember_me'
  # ...
end

# /features/step_definitions/common_steps.rb
Then(/^I see unchecked box$/) do
  LoginPage.on do
    is_expected.to have_remember_me_element(unchecked: true)
  end
end
```
I will close the issue as an incorrect capybara options usage.

**Closed by romikoops** 2017-06-27 09:25 UTC
